@baseUrl = http://localhost:3333

GET {{baseUrl}}/health
###
GET {{baseUrl}}/rooms
###
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Room Test",
  "description": "Room test created from Resqt Client extension request."
}
